language: generic
sudo: required
env:
    matrix:
        - OS_TYPE=debian OS_ARCH=amd64 OS_VERSION=stretch
        #- OS_TYPE=debian OS_ARCH=i386 OS_VERSION=stretch
        - OS_TYPE=debian OS_ARCH=amd64 OS_VERSION=buster
        #- OS_TYPE=debian OS_ARCH=i386 OS_VERSION=jessie
services:
    - docker
before_install:
    - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"'
        | sudo tee /etc/default/docker > /dev/null
    - sudo service docker restart
    - sleep 5
    - sudo docker pull ${OS_TYPE}:${OS_VERSION}
script:
    - sudo docker run --rm=true -v `pwd`:/base-src:rw -t ${OS_TYPE}:${OS_VERSION} /bin/bash
        -c /base-src/ci/${OS_TYPE}.sh
    - sudo chown `id -u`:`id -g` -R deb
deploy:
    provider: releases
    skip_cleanup: true
    on:
      tags: true
    api_key:
        secure: i9uLeiM+e9I8ZKbxvJ8Ih8NicaDGnbZbDFV/mdC5yrBSE9efNdH6wPx1S9gd8ejcTq+F65mExZF5Wa25l0jo+sBdGNR2vKiqLs89Tm/CHQ47ZkUQwMWDbLZvGoBuAX8fcEa7EqE6Tp5T5b93rwSxTls+xfQ6VCZ289V+Zww9jnMECiX9FBLVMYySfQZ31ZLn1UuAV7FyfDQfu1x4C60rUT2hyfR7Q9JGlVfsCNDb8IJ5RDuG25D7hxQrwSMFyxsYIL2vJG5fXFmIAofrn8Uyzzdcg9CNjYRfzPRamO8Fze9rXyR0f8xhyoBrXu+HtJ7m4YhgXuDIhLzeLfLeYzi9uMuDpioyHOGed3uewPq6fNYOwquFo+JXPTFyu8CsdKvGOhb5HEJlYvooRxKeOKfpFjuqF2bOARBkAsP13mSik2Er1VXoDYLjYi1UGSaW5aLm9EXeU992DxBVCDiH/BuEW1V8IRD7J9DJdD9DaAXPFpFFrlTemR5SOHbNV8Qt64RIBj2CmZ5sJRaIMBTdyx0d1L0/gFnkMxLVZnPZzXBPUDEQ33bKZlqCCuU0XLCsmOytYExcAaQceVIF15NO47HwK9HhKnAYKSY0UCFqdxQfZ+AGTwhz8rssX5CsadTbQFSZ7JhotAtZpkZFzgencrUBKcvgrioUz8xcDcJTBgH/G7Q=
    file_glob: true
    file: deb/*
